config/routes.rb
Rails.application.routes.draw do
  resources :projects

  devise_for :users

  root 'home#index'
  resources :projects do
    resources :blog_posts, only: ['show', 'create', 'update', 'edit', 'destroy']
    resources :images, only: ['index', 'create', 'edit', 'update', 'destroy']
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :blog_posts
  has_many :images
  belongs_to :cover_image, class: Image

  validates :name, presence: true
  validates :category, presence: true
  validates :description, presence: true
  validates :name, uniqueness: {scope: :user_id}

  def self.categories
    %w{electronics software home-improvement crafts}.map{|c| [c.titleize, c] }
  end

  def thumbnail_url
    if cover_image.present?
      cover_image.image.url(:thumb)
    else
      nil
    end
  end

  def cover_image_url
    if cover_image.present?
      cover_image.image.url
    else
      ''
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :my_project, only: [:edit, :update, :destroy]
  respond_to :html

  def index
    @projects = Project.all
    respond_with(@projects)
  end

  def show
    @blog_post = BlogPost.new(text: @project.unfinished_post, project: @project) if @project.user == current_user
    @markdown_parser = markdown_parser(@project)
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if params[:cover] && params[:cover][:image].present?
      @img = Image.new(image: params[:cover][:image], project: @project)
    elsif params[:cover] && params[:cover][:image_url].present?
      @img = Image.new(image: URI.parse(params[:cover][:image_url]).to_s, project: @project)
    end

    @project.cover_image = @img if @img

    if @img && !@img.valid?
      render 'new'
      return
    end

    if @project.save
      respond_with(@project)
    else
      render 'new'
    end
  end

  def update
    if @project.update(project_params)
      respond_with(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private

  def my_project
    p = Project.find(params[:id])
    if p.user_id != current_user.id
      flash[:alert] = "You are not the owner of this project"
      redirect_to project_url(p)
    end
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :user_id, :category, :description, :thumbnail, :unfinished_post)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% if @project.errors.any? || (@img && @img.errors.any?) %>
    <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
            <div class="alert alert-danger">
                <ul>
                    <% @project.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                    <% if @img && @img.errors.any? %>
                        <% @img.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
<% end %>

<%= form_for(@project, html: {multipart: true}) do |f| %>
    <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= f.label :category %>
                <select name="project[category]" id="project_category" class="form-control">
                    <% Project.categories.each do |c| %>
                        <option value="<%=c[1] %>"><%= c[0] %></option>
                    <% end %>
                </select>
            </div>

            <% if @project.new_record? %>
                <hr/>

                <div class="form-group">
                    <%= label nil, nil, "Provide a cover image (jpg, png, or gif):" %>
                </div>

                <div class="form-group">
                    <%= label :cover, :image, "Upload file" %>
                    <%= file_field :cover, :image, accept: "image/jpg,image/jpeg,image/png,image/gif", class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= label :cover, :image_url, "Use URL" %>
                    <%= url_field :cover, :image_url, class: 'form-control' %>
                </div>
            <% end %>

            <hr/>

            <div class="form-group">
                <%= f.label :description, "Short description" %>
                <%= f.text_area :description, class: 'form-control', rows: 3 %>
            </div>

            <%= f.submit class: 'btn btn-default' %>
        </div>
    </div>
<% end %>

app/views/projects/_header.html.erb
<div class="row">
    <div class="col-xs-12">
        <h1><%= link_to @project.name, project_path(@project) %></h1>
        by
        <%= @project.user.username %>

        <% if current_user == @project.user %>
            <span class="pull-right">
                <%= link_to 'Edit', edit_project_path(@project) %>
                |
                <%= link_to "Manage images", project_images_path(@project) %>
            </span>
        <% end %>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        Started on <%= @project.created_at.strftime("%b %-d %Y, %H:%M:%S") %>
    </div>
</div>

app/views/projects/_images.html.erb
<div class="row">
    <div class="col-xs-12">
        <%= link_to @project.cover_image_url, target: '_blank', id: "large_image" do %>
            <img src="<%= @project.cover_image_url %>"/>
        <% end %>
    </div>
</div>

<div class="row">
    <div class="col-xs-12" id="image_caption">
        <%= @project.cover_image.try(:name) %>
    </div>
</div>

<% if @project.user == current_user %>
    <div class="row">
        <div class="col-xs-12" id="image_controls">
            <span class="pull-left">Link to this image:&nbsp;</span>
            <code class="pull-left">![](image_<span id="link_image_id"><%= @project.cover_image_id %></span>)</code>
        </div>
    </div>
<% end %>

<div class="row">
    <div class="col-xs-12">
        <% @project.images.each do |image| %>
            <%= link_to "#", class: 'project-thumbnail' do
            %><img src="<%= image.image.url(:thumb) %>"
                   alt="<%= image.name %>"
                   title="<%= image.name %>"
                   data-id="<%= image.id %>"
                   data-url="<%= image.image.url %>"/><% end %>
        <% end %>
    </div>
</div>

app/views/projects/edit.html.erb
<div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <h1>Edit project</h1>
    </div>
</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.user_id %></td>
        <td><%= project.category %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<% provide :new_project_link_active, "class=\"active\"".html_safe %>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <h1>Start a new project</h1>        
    </div>
</div>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="row" id="controls">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <%= render partial: 'header' %>

        <hr/>

        <% if @project.images.any? %>
            <%= render partial: 'images' %>
            <hr/>
        <% end %>

        <div class="row">
            <div class="col-xs-12">
                <%= raw(@markdown_parser.render(@project.description)) %>
            </div>
        </div>

        <% if @project.user == current_user %>
            <hr/>
            <%= render partial: 'blog_posts/form', locals: {blog_post: @blog_post} %>
        <% end %>

        <% @project.blog_posts.order("created_at desc").each do |post| %>
            <hr/>

            <div class="row">
                <div class="col-xs-12">
                    <a href="<%= project_blog_post_url(@project, post) %>">
                        <strong><%= post.created_at.strftime("%b %-d %Y, %H:%M:%S") %></strong>
                    </a>

                    <% if @project.user == current_user %>
                        <span class="pull-right">
                            <%= link_to "Edit", edit_project_blog_post_path(@project, post), class: 'small' %>
                            |
                            <%= link_to "Delete", project_blog_post_path(@project, post), method: 'delete', class: 'small', data: { confirm: "Are you sure?" } %>
                        </span>
                    <% end %>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 blog-post">
                    <%= raw(@markdown_parser.render(post.preview_text)) %>
                </div>
            </div>
        <% end %>
    </div>
</div>