config/routes.rb
Rails.application.routes.draw do
  resources :projects

  devise_for :users

  root 'home#index'
  resources :projects do
    resources :blog_posts, only: ['show', 'create', 'update', 'edit', 'destroy']
    resources :images, only: ['index', 'create', 'edit', 'update', 'destroy']
  end

end

app/models/image.rb
# Encoding: utf-8

class Image < ActiveRecord::Base
  belongs_to :project
  if Rails.env.production?
    has_attached_file(:image, styles: {thumb: "100x100>"},
                      storage: :s3,
                      s3_credentials: {
                        bucket: ENV['S3_BUCKET'],
                        access_key_id: ENV['ACCESS_KEY_ID'],
                        secret_access_key: ENV['SECRET_ACCESS_KEY']
                      })

  else
    has_attached_file(:image, styles: {thumb: "100x100>"})
  end

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_attachment :image, presence: true
  validates :project, presence: true
end

app/controllers/images_controller.rb
# Encoding: utf-8

class ImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_image, only: [:update, :destroy, :edit]
  before_action :set_project
  before_filter :my_project_and_image, except: [:index, :create]
  before_filter :my_project, only: [:index, :create]

  respond_to :html, :json

  def index
    @images = @project.images
    @image = Image.new
  end

  def create
    if params[:image]
      @image = Image.new(image_params)
    elsif params[:image_url]
      @image = Image.new(image_from_url_params)
    end

    if @image.save
      flash[:notice] = "Image added"
      redirect_to edit_project_image_url(@project, @image)
    else
      flash[:alert] = "Couldn't add this image: #{@image.errors.full_messages.to_sentence}"
      redirect_to project_images_url(@project)
    end
  end

  def update
    if @image.update(image_update_params)
      if params[:cover_image] && @project.cover_image != @image
        @project.update_attribute :cover_image, @image
      elsif !params[:cover_image] && @project.cover_image == @image
        @project.update_attribute :cover_image, nil
      end

      flash[:notice] = "Image updated"
      redirect_to project_images_url(@project)
    else
      flash[:alert] = "Couldn't update this image: #{@image.errors.full_messages.to_sentence}"
      render 'edit'
    end
  end

  def destroy
    if @project.cover_image == @image
      @project.update_attribute :cover_image, nil
    end

    @image.destroy
    flash[:notice] = "Image deleted"
    redirect_to project_images_url(@project)
  end

  private

  def my_project
    p = Project.find(params[:project_id])
    if p.user_id != current_user.id
      flash[:alert] = "You are not the owner of this project"
      redirect_to project_path(@project)
    end
  end

  def my_project_and_image
    p = Project.find(params[:project_id])
    i = Image.find(params[:id])

    if p.user_id != current_user.id || i.project != p
      flash[:alert] = "You are not the owner of this image"
      redirect_to project_url(p)
    end
  end

  def set_image
    @image = Image.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def image_update_params
    params.require(:image).permit(:name)
  end

  def image_params
    p = params.require(:image).permit(:name, :image)
    p[:project_id] = params[:project_id]
    p
  end

  def image_from_url_params
    { project_id: params[:project_id],
      image: params.require(:image_url) }
  end
end

app/views/images/edit.html.erb
<div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <%= render partial: 'projects/header' %>
        <hr/>

        <div class="row">
            <div class="col-xs-12">
                <%= link_to @image.image.url, target: '_blank', id: "large_image" do %>
                    <img src="<%= @image.image.url %>"/>
                <% end %>
            </div>
        </div>

        <hr/>

        <div class="row">
            <div class="col-xs-12">
                <%= form_for @image, url: project_image_url(@project, @image) do |f| %>
                    <div class="form-group">
                        <%= f.label :name, "Description" %>
                        <%= f.text_area :name, class: 'form-control', rows: 5 %>
                    </div>

                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <%= check_box_tag 'cover_image', '1', (@image == @project.cover_image) %>
                                Project cover image
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <%= f.submit "Update", class: 'btn btn-primary pull-right' %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/images/index.html.erb
<div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <%= render partial: 'projects/header' %>

        <hr/>

        <div class="row">
            <%= form_for @image, url: project_images_path(@project), html: {multipart: true} do |f| %>
                <div class="col-xs-8">
                    <%= f.file_field :image, class: 'form-control' %>
                </div>
                <div class="col-xs-4">
                    <%= f.submit "Upload image", class: 'form-control btn btn-success' %>
                </div>
            <% end %>
        </div>

        <div class="row">
            <div class="col-xs-12">&nbsp;</div>
        </div>

        <div class="row">
            <%= form_for @image, url: project_images_path(@project), html: {multipart: true} do |f| %>
                <div class="col-xs-8">
                    <input name="image_url" type="url" class="form-control" placeholder="Image URL"/>
                </div>
                <div class="col-xs-4">
                    <%= f.submit "Add from URL", class: 'form-control btn btn-success' %>
                </div>
            <% end %>
        </div>

        <hr/>

        <% @images.each do |image| %>
            <div class="row image-row">
                <div class="col-xs-12">
                    <a href="<%= image.image.url %>" target="_blank" class="pull-left">
                        <div class="project-thumbnail" style="background-image:url(<%= image.image.url(:thumb) %>)"></div>
                    </a>

                    <div class="pull-left">
                        <% if image.name.present? %>
                            <%= image.name %>
                        <% else %>
                            <em class="text-muted">No description</em>
                        <% end %>
                    </div>

                    <div class="pull-right">
                        <%= link_to "Edit", edit_project_image_path(@project, image) %>
                        |
                        <% if image == @project.cover_image %>
                            <span class="text-success">&#10003; Cover image</span>
                        <% else %>
                            <%= link_to "Delete", project_image_path(@project, image), method: :delete, data: {confirm: "Are you sure?"} %>
                        <% end %>
                    </div>
                </div>
            </div>

            <hr/>
        <% end %>
    </div>
</div>